### PR TITLE
Persistent side effects with Dir, File and FileUtils

### PR DESCRIPTION
**Pull request by crabonature**
PR for #90.

### CODE REVIEW

**Comment by jwoertink** [comment]
Hey! thanks for submitting the PR. I'll take a look over this. One thing I am wondering just off the top of my head, when you check the `with_persistent_side_effect`, I'm wondering if any File operation would also fall in to this.

**Comment by crabonature** [comment]
So I checked `File` and `FileUtils` and this ones will be falling into this too:
```crystal
File.delete(), File.link(), File.rename(), File.symlink()
FileUtils.mkdir(), FileUtils.mkdir_p(), FileUtils.mv(),
FileUtils.rm, FileUtils.rm_r(), FileUtils.rm_rf(), FileUtils.rmdir()
```

**Comment by veelenga** [comment]
@jwoertink @crabonature I don't think we can handle this properly. Instead, I would suggest to add it to the [list of side effects](https://github.com/crystal-community/icr/blob/master/src/icr/cli.cr#L30-L33).

**Comment by veelenga** [comment]
Closing it. Please do not hesitate to continue the discussion if you have something to say. Thank you.

**Pull request closed without merging**
