### PR TITLE
Added a "clear"-command to clear the screen

### PR DESCRIPTION
**Pull request by Jens0512**
Not too sure if the C-bindings work in every unix system, but i hope so.

### CODE REVIEW

**Comment by veelenga** [comment]
@Jens0512 thanks for your contribution.

Your change works for me on OS X and overall it is good, but could you please explain why we need this in ICR? Personally, I very rarely use `clear` command in a terminal and probably will never use it in REPL.

**Comment by Jens0512** [comment]
@veelenga Well, of course we don't *need* one. But i think some people would like to clean their screen sometimes, and some (like myself) are extremely frequent screen-cleaners. 
Im not so sure about the invoke though, "clean" is not an all that unusual method/function -name. And its probably better to just don't have a clear-command than changing the name to clean_screen or so 😅, but its a suggestion.

**Comment by jwoertink** [comment]
On Mac I just do `cmd-k` or `cmd-l` depending on my needs. On linux I think it's `ctrl-shift-l`. I'm totally on board with needing to clean the screen every 5 seconds, but I think keyboard shortcuts are a lot easier to do. I'm thinking maybe we do a community vote to see if this is something everyone would prefer?

**Comment by Jens0512** [comment]
@jwoertink Well, to me it seems like the reasons for not having it are quite superior already.

**Comment by Jens0512** [comment]
Closed as there was no need of the clear-command. Instead `use cmd+k` on mac, or `ctrl-shift-l` on  linux

**Comment by jwoertink** [comment]
Cool, that works. Thanks for the contribution! Maybe you can help me out with #41 @Jens0512 😄

**Pull request closed without merging**
