### PR TITLE
Crystal next support

### PR DESCRIPTION
**Pull request by veelenga**
https://github.com/crystal-lang/crystal/releases/tag/0.24.0 (pre-release)

Shouldn't be merge until the official release

### CODE REVIEW

**Comment by veelenga** [comment]
https://github.com/crystal-lang/crystal/releases/tag/v0.24.1 is out. Ready for review/merge.

**Comment by jwoertink** [comment]
Looks good to me. Didn't there used to be a button to approve? I'm not seeing it, but I approve the changes 👍

**Comment by veelenga** [comment]
Should we prepare a new release for this?

**Comment by oprypin** [comment]
Why yes, you should

**Pull request merged**
