### PR TITLE
Last result local '__'

### PR DESCRIPTION
**Pull request by veelenga**
Inspired by https://github.com/pry/pry/wiki/Special-Locals#Last_result

```crystal
icr(0.23.1) > a = 42
 => 42
icr(0.23.1) > __
 => 42
icr(0.23.1) > __ + 1
 => 43
icr(0.23.1) > 1 + __
 => 44
icr(0.23.1) > __.to_s
 => "44"
icr(0.23.1) > __.to_i
 => 44
icr(0.23.1) > inc = -> { __ + 1 }
 => #<Proc(Int32):0x1002ea350>
icr(0.23.1) > inc.call
 => 45
...
```

cc @jwoertink

### CODE REVIEW

**Comment by jwoertink** [comment]
Beautiful! I think it looks nice, and doesn’t feel awkward. Plus the change is pretty minimal. :+1:

**Comment by veelenga** [comment]
@greyblake @crystal-community WDYT?

**Comment by veelenga** [comment]
Hey guys. Can I merge this?

**Comment by greyblake** [comment]
I think yes.
Would someone mind adding a description of this feature to README?

**Comment by veelenga** [comment]
@greyblake thanks. Added in #64

**Pull request merged**
